# Generated by Django 5.2.12 on 2026-03-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='budget_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='budget_currency',
            field=models.CharField(blank=True, default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='budget_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
