# Generated by Django 6.0 on 2026-03-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_add_budget_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
